### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by jhok2013** [tiangolo/typer#240] opened 2021-02-25 04:55 UTC
Hello! Excellent work for making such a great tool. I am running into a problem with subcommands. I get a NameError: name <command name> is not defined error when adding a command to another app.

An example of the sub command is created like this in a separate file named message.py.
```{python}
import typer

app = typer.Typer()

@app.command()
def message():
    typer.echo(f'Message sent')

if __name__ == '__main__':
    app()
```

I then have a different cli that is importing that command and adding it to the an app, like so.

```{python}
import typer
import message

app = typer.Typer()
app.add_typer(message.app, name='message')

@app.command()
def main():
    typer.echo('App starting')

if __name__ == '__main__':
    app()
```

**Comment by daddycocoaman** [comment] 2021-02-26 21:51
I was unable to produce the error with the code you provided. Everything seems to be in order with that code too. Maybe something different in your actual code?

**Comment by graue70** [comment] 2021-03-04 13:39
I cannot reproduce the error either. The provided code runs fine.

**Comment by tibeer** [comment] 2022-07-08 11:16
Also unable to reproduce. Would suggest that this can be closed A) due to being unable to reproduce it and B) because it's fairly old.

**Comment by svlandeg** [comment] 2024-07-16 15:29
[Maintenance note]: I'll go ahead and close this issue as the issue could not be reproduced. Thanks all for the feedback! 🙏

**Closed by svlandeg** 2024-07-16 15:29 UTC
Labels: bug
